### PR TITLE
Revert "Minor refactoring"

### PR DESCRIPTION
**Pull request by JeremyWildsmith**
Reverts JeremyWildsmith/bazaarbot-java#7

Currently these changes are causing the unit test to fail.

### CODE REVIEW

**Comment by DigitalSmile** [comment]
Can you please provide the information why it is failing? I can see the result of test failed on the bankrupt method (not implemented), which is no actually the test failure...

**Comment by DigitalSmile** [comment]
And I am now on a separate brach which holds all refactoring things. I will create a separate pull request, instead of reverting my previous efforts.

**Comment by JeremyWildsmith** [comment]
The failure was basically that the refactor changed the overall behaviour of the simulation... but I can see now that it is going to be very difficult to make the entire system deterministic. I.e. using sets / maps will break the determinism of the simulation. Its just too delicate.

I think we need a better way to unit test.

And yeah I understand that reverting these was a huge pain to you and I apologies for the inconvenience.

Thanks!

**Comment by DigitalSmile** [comment]
That's fine, just wanna be sure I really did not break something important :)
Will create a new PR with all other branches integrated

**Pull request merged**
