### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by DigitalSmile**
Can you please have a look?
I did not merge #20 it is way to complicated to do without getting the idea :)

### CODE REVIEW

**Comment by DigitalSmile** [comment]
Awh... It did not get my changes in refactoring all other classes.

**Comment by DigitalSmile** [comment]
I guess it would be easier to revert my previous PR and manually put all needed changes with contracts you have made...

**Comment by JeremyWildsmith** [comment]
I think what I'll do is pull your changes and then manually move them over be referencing the diff; and then I'll create a different PR; I think that'd be easier than trying to resolve the merge conflicts. I'll try to get it done this evening. :)

**Comment by JeremyWildsmith** [comment]
Hmm yeah this is too difficult to merge. I tried and I just ended up breaking something. I think it'd be better to re-apply the changes on-top of the current state of master manually. If you don't mind doing that?

I'll definitely be more careful with these merges from now on. Also I'll try to avoid making any changes to the existing code after tonight. I think two people refactoring at the same time is a recipe for disaster haha. 

I'll just do some research into market simulation / contracts etc in the mean time. I'm also doing some work to get this project accessible from the Maven repository and do some documentation (though I understand it may change, it will be nice to have a template.)

**Comment by DigitalSmile** [comment]
Okay, I will close this PR.

**Pull request closed without merging**
